#!/usr/bin/env zsh

set -eu

# Canonical build variables expected by Xcode project settings:
# - STAGING: used by Debug configuration
# - PROD: used by Release configuration
#
# Legacy names (BASE_URL_STAGING / TOKEN_STAGING ...) and single-name aliases
# are supported for migration. If STAGING values are not set, PROD values are used as
# a safe local fallback for quick testing.
#
# Usage:
#   source scripts/context-server-env.sh
#   # then run xcodebuild / open Xcode from the same terminal

pick_env() {
  local names=("$@")
  local name
  local value
  for name in "${names[@]}"; do
    value="${(P)name:-}"
    if [[ -n "${value}" ]]; then
      print -n "$value"
      return 0
    fi
  done
  print -n ""
}

export CONTEXT_SERVER_STAGING_BASE_URL="$(pick_env CONTEXT_SERVER_STAGING_BASE_URL CONTEXT_SERVER_BASE_URL_STAGING CONTEXT_SERVER_BASE_URL CONTEXT_SERVER_PROD_BASE_URL)"
export CONTEXT_SERVER_STAGING_TOKEN="$(pick_env CONTEXT_SERVER_STAGING_TOKEN CONTEXT_SERVER_TOKEN_STAGING CONTEXT_SERVER_TOKEN CONTEXT_SERVER_PROD_TOKEN)"
export CONTEXT_SERVER_STAGING_CLIENT_ID="$(pick_env CONTEXT_SERVER_STAGING_CLIENT_ID CONTEXT_SERVER_CLIENT_ID_STAGING CONTEXT_SERVER_CLIENT_ID CONTEXT_SERVER_PROD_CLIENT_ID)"
export CONTEXT_SERVER_STAGING_CERTIFICATE_PIN_SHA256="$(pick_env CONTEXT_SERVER_STAGING_CERTIFICATE_PIN_SHA256 CONTEXT_SERVER_STAGING_CERTIFICATE_PIN CONTEXT_SERVER_CERTIFICATE_PIN_SHA256 CONTEXT_SERVER_CERTIFICATE_PIN CONTEXT_SERVER_PROD_CERTIFICATE_PIN_SHA256 CONTEXT_SERVER_PROD_CERTIFICATE_PIN)"
export CONTEXT_SERVER_STAGING_CERTIFICATE_PIN="${CONTEXT_SERVER_STAGING_CERTIFICATE_PIN:-${CONTEXT_SERVER_STAGING_CERTIFICATE_PIN_SHA256:-}}"
export CONTEXT_SERVER_STAGING_SIGNING_SECRET="$(pick_env CONTEXT_SERVER_STAGING_SIGNING_SECRET CONTEXT_SERVER_SIGNING_SECRET_STAGING REQUEST_SIGNING_SECRET CONTEXT_SERVER_SIGNING_SECRET CONTEXT_SERVER_PROD_SIGNING_SECRET)"

export CONTEXT_SERVER_PROD_BASE_URL="$(pick_env CONTEXT_SERVER_PROD_BASE_URL CONTEXT_SERVER_BASE_URL_PROD CONTEXT_SERVER_BASE_URL)"
export CONTEXT_SERVER_PROD_TOKEN="$(pick_env CONTEXT_SERVER_PROD_TOKEN CONTEXT_SERVER_TOKEN_PROD CONTEXT_SERVER_TOKEN)"
export CONTEXT_SERVER_PROD_CLIENT_ID="$(pick_env CONTEXT_SERVER_PROD_CLIENT_ID CONTEXT_SERVER_CLIENT_ID_PROD CONTEXT_SERVER_CLIENT_ID)"
export CONTEXT_SERVER_PROD_CERTIFICATE_PIN_SHA256="$(pick_env CONTEXT_SERVER_PROD_CERTIFICATE_PIN_SHA256 CONTEXT_SERVER_PROD_CERTIFICATE_PIN CONTEXT_SERVER_CERTIFICATE_PIN_SHA256 CONTEXT_SERVER_CERTIFICATE_PIN)"
export CONTEXT_SERVER_PROD_CERTIFICATE_PIN="${CONTEXT_SERVER_PROD_CERTIFICATE_PIN:-${CONTEXT_SERVER_PROD_CERTIFICATE_PIN_SHA256:-}}"
export CONTEXT_SERVER_PROD_SIGNING_SECRET="$(pick_env CONTEXT_SERVER_PROD_SIGNING_SECRET CONTEXT_SERVER_SIGNING_SECRET_PROD CONTEXT_SERVER_SIGNING_SECRET REQUEST_SIGNING_SECRET)"

mask() {
  local value="$1"
  if [[ -z "$value" ]]; then
    print "미설정"
    return
  fi

  local len=${#value}
  if (( len <= 8 )); then
    print "********"
    return
  fi

  local head="${value:0:4}"
  local tail="${value: -4}"
  print "${head}...${tail}"
}

echo "Context Server build env loaded:"
echo "  STAGING_BASE_URL=${CONTEXT_SERVER_STAGING_BASE_URL:-}"
echo "  STAGING_CLIENT_ID=${CONTEXT_SERVER_STAGING_CLIENT_ID:-}"
echo "  STAGING_TOKEN=$(mask "${CONTEXT_SERVER_STAGING_TOKEN:-}")"
echo "  STAGING_SIGNING_SECRET=$(mask "${CONTEXT_SERVER_STAGING_SIGNING_SECRET:-}")"
echo "  STAGING_CERTIFICATE_PIN_SHA256=$(mask "${CONTEXT_SERVER_STAGING_CERTIFICATE_PIN_SHA256:-}")"
echo "  PROD_BASE_URL=${CONTEXT_SERVER_PROD_BASE_URL:-}"
echo "  PROD_CLIENT_ID=${CONTEXT_SERVER_PROD_CLIENT_ID:-}"
echo "  PROD_TOKEN=$(mask "${CONTEXT_SERVER_PROD_TOKEN:-}")"
echo "  PROD_SIGNING_SECRET=$(mask "${CONTEXT_SERVER_PROD_SIGNING_SECRET:-}")"
echo "  PROD_CERTIFICATE_PIN_SHA256=$(mask "${CONTEXT_SERVER_PROD_CERTIFICATE_PIN_SHA256:-}")"
