#!/bin/bash
# Generate SecretsBootstrap.swift from build settings.
# Add this as a "Run Script" build phase in Xcode BEFORE "Compile Sources".
# Input: Build settings from Secrets.xcconfig (resolved by Xcode)
# Output: SecretsBootstrap.swift (gitignored, compiled into binary)

OUTPUT="${SRCROOT}/readtap/Platform/Infrastructure/SecretsBootstrap.swift"

cat > "$OUTPUT" << SWIFT
// Auto-generated by generate_secrets.sh — DO NOT EDIT or commit.
import Foundation

enum SecretsBootstrap {
    static let contextServerToken = "${CONTEXT_SERVER_TOKEN}"
    static let contextServerSigningSecret = "${CONTEXT_SERVER_SIGNING_SECRET}"
    static let krdictApiKey = "${KRDICT_API_KEY}"

    /// Seed Keychain stores on first launch. Safe to call multiple times.
    static func seedKeychainIfNeeded() {
        let key = "secrets_keychain_seeded_v1"
        guard !UserDefaults.standard.bool(forKey: key) else { return }

        if !contextServerToken.isEmpty {
            ContextServerTokenStore.save(contextServerToken)
        }
        if !contextServerSigningSecret.isEmpty {
            ContextServerSigningSecretStore.save(contextServerSigningSecret)
        }
        if !krdictApiKey.isEmpty {
            KoreanDictKeyStore.save(krdictApiKey)
        }
        UserDefaults.standard.set(true, forKey: key)
    }
}
SWIFT
